### PR TITLE
Use operator image from GHCR

### PR DESCRIPTION
**Pull request by pavolloffay**
https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fopentelemetry-operator

### CODE REVIEW

**Review by VineethReddy02 — APPROVED** [review]
LGTM!

cc @jpkrohling

**Review by jpkrohling — APPROVED** [review]
Are those the only places we use Quay?

**Comment by pavolloffay** [comment]
The target allocator is hosted on quay.

**Comment by jpkrohling** [comment]
The next step is then to change it to also use GHCR.

**Comment by pavolloffay** [comment]
I leave this for the maintainer of that component

**Pull request merged**
