### PR TITLE
Add doc and e2e for sidecar

### LINKED ISSUE #214: Sidecar injection by instance name not documented
I've been looking through source code and issues to try to understand how to use the sidecar injection. It looks like the annotation can be either "true" or an OpenTelemetryCollector instance name.  I haven't been able to get it working yet, but I'm not sure if that's because the operator is misconfigured or my annotations are incorrect.

Here's what I've gathered from the source code and the CRD yaml

### Annotations

`sidecar.opentelemetry.io/inject` can be one of `true`, `false`, or an instance name. I take this to mean that it can refer to a specific instance of an OpenTelemetryCollector.

### Collector configuration

`spec.mode` can be one of 
* daemonset
* deployment
* sidecar

If set to sidecar mode it will only create an instance if it's referenced by an annotation on a Deployment.

In my case I want a custom configuration for a specific Deployment so it appears I have to create an instance of an OpelTelemetryCollector and reference it by name in the Deployment's sidecar.opentelemetry.io/inject` annotation. However, no sidecars are injected and I don't see anything interesting in the logs for the opentelemetry controller manager.

Should the following work?

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-custom-collector
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    exporters:
      otlp:
        endpoint: upstream:4317
        insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
  annotations:
    "sidecar.opentelemetry.io/inject": "my-custom-collector"
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: m-app
    spec:
      containers:
# etc
```

### PR DESCRIPTION
**Pull request by jpkrohling**
Closes #214 by documenting how the sidecar injection should work and added a smoke test for the basic use case of sidecars.

﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
@tigrannajaryan , @bogdandrutu would one of you please review this one?

**Comment by tigrannajaryan** [comment]
I don't have experience with operators or sidecars, so unfortunately cannot help much here.

**Comment by jcchavezs** [comment]
LGTM

**Comment by jpkrohling** [comment]
@tigrannajaryan would it be OK to merge based on @jcchavezs' approval?

**Comment by jcchavezs** [comment]
I am just started to get involved in collector work so probably you need an
official approval.

**Comment by jpkrohling** [comment]
@jcchavezs your approval is appreciated, even if extra officially.

**Review by tigrannajaryan — APPROVED** [review]

**Pull request merged**
