### PR TITLE
[chore] Build and publish application hosted in the repository for the DotNet instrumentation E2E test

### PR DESCRIPTION
**Pull request by iblancasa**
Related to https://github.com/open-telemetry/opentelemetry-operator/issues/2073.

The test migration will be done in a follow up PR after publishing the image.

### CODE REVIEW

**Review by TylerHelmuth — COMMENTED** [review]
From the issue, @pavolloffay mentions one of the goals is to `improve maintenance`, and I don't think introducing our own test app is going to help with that.  If we introduce a test app for each auto-instrumentation language we'll end up with a repo with many different languages to maintain and then the burden of maintaining those test apps. I'd much rather depend on pre-existing, small, stable test apps.

**Comment by pavolloffay** [comment]
>  @pavolloffay do you think there's value in publishing multiple app images we only maintain for E2E tests?

Is there a better alternative? We need a small test app that can run in isolation and the image is published for (amd64, arm64, s390x, ppc64). 



This PR can be made much simpler. Only a single controller is needed, we don't need to include JS and HTLM code.

**Comment by iblancasa** [comment]
> This PR can be made much simpler. Only a single controller is needed, we don't need to include JS and HTLM code.

I just wanted to keep the application as it was created by the cli. I'll remove the "extra" files.

**Comment by swiatekm-sumo** [comment]
> > @pavolloffay do you think there's value in publishing multiple app images we only maintain for E2E tests?
> 
> Is there a better alternative? We need a small test app that can run in isolation and the image is published for (amd64, arm64, s390x, ppc64).
> 
> This PR can be made much simpler. Only a single controller is needed, we don't need to include JS and HTLM code.

Why do we need it to be published? So it's possible to run tests on different archs than Github Runners support, outside of the project's normal CI process?

**Comment by pavolloffay** [comment]
> Why do we need it to be published? 

I don't have a strong opinion, but those tests app won't change much (at least they have never changed in our e2e tests). If they are published it will speed up CI. If they are published we could also use them for debugging.

**Comment by swiatekm-sumo** [comment]
> > Why do we need it to be published?
> 
> I don't have a strong opinion, but those tests app won't change much (at least they have never changed in our e2e tests). If they are published it will speed up CI. If they are published we could also use them for debugging.

I'm less concerned about the maintenance burden of the app itself, and more about the burden of maintaining these artifacts. Every additional CI workflow that publishes something to GHCR is another opportunity for issues that we'd then need to spend time fixing.

In some respect, the fact that the workflow in this PR only runs when the app is changed helps with this, but then we'll get all the issues at once when we make a change a year from now. Maybe this is ok, though... @iblancasa do you have a sense of how many of these apps we're going to need, this one included?

**Comment by iblancasa** [comment]
> do you have a sense of how many of these apps we're going to need, this one included?

@swiatekm-sumo I would say these ones:
- [Apache HTTPD](https://github.com/open-telemetry/opentelemetry-operator/pull/2085)
- [Java](https://github.com/open-telemetry/opentelemetry-operator/pull/2094)
- [DotNet](https://github.com/open-telemetry/opentelemetry-operator/pull/2082)
- [Python](https://github.com/open-telemetry/opentelemetry-operator/pull/2095)
- Go (I'm on it)

**Comment by swiatekm-sumo** [comment]
I'd like to discuss this during the SIG meeting tomorrow to make sure we have consensus among maintainers. Sorry for holding this PR up with this @iblancasa, the actual content of it looks good to me.

**Review by swiatekm-sumo — APPROVED** [review]
LGTM

**Comment by iblancasa** [comment]
Can we merge this?

**Comment by jaronoff97** [comment]
Is the plan for the other jobs to just extend this one?

**Comment by iblancasa** [comment]
> Is the plan for the other jobs to just extend this one?

Sorry. I just saw this comment.

I did a reusable workflow to make everything easier.

**Pull request merged**
