### PR TITLE
Fix for Target Allocator not saving targets when collector instances take time to come up

### PR DESCRIPTION
**Pull request by rashmichandrashekar**
**Description:** 
Fixing a bug - In a kubernetes cluster, have scrape jobs configured using TargetAllocator. Due to timing issue(which is very common with kubernetes clusters, where no ordering can be guaranteed), the instances are not discovered until after the first set of targets are discovered. The configuration applied until the instances are discovered are lost.
This PR fixes that issue where it saves the targets until the collector instances come up

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-operator/issues/2350

**Testing:** 
Tested that in such scenarios, the targets are not lost and assigned to collector instances when they come up

### CODE REVIEW

**Comment by swiatekm-sumo** [comment]
Can you add a unit test for this case?

Also, does the same problem not apply to the other allocation strategy as well?

**Comment by rashmichandrashekar** [comment]
> Can you add a unit test for this case?
> 
> Also, does the same problem not apply to the other allocation strategy as well?

Thanks @swiatekm-sumo. I have made the changed for the other hashing algo as well and added a couple unit tests. please lmk if anything else is needed.

**Comment by swiatekm-sumo** [comment]
Can you also check the case where you add targets to a strategy with 0 collectors, and later add collectors to see if targets get allocated to them correctly?

There's also a lint error you need to fix.

**Comment by rashmichandrashekar** [comment]
> Can you also check the case where you add targets to a strategy with 0 collectors, and later add collectors to see if targets get allocated to them correctly?
> 
> There's also a lint error you need to fix.

Thanks @swiatekm-sumo . That's a good test case, I have added that. Please take a look.

**Comment by rashmichandrashekar** [comment]
@swiatekm-sumo - I see an e2e test failure due to timeouts during [CR creation](https://github.com/open-telemetry/opentelemetry-operator/actions/runs/6894688215/job/18757056049#step:6:359). Could you please rerun the tests? Thanks!

**Comment by rashmichandrashekar** [comment]
@swiatekm-sumo - All the checks seem to have passed, could you pls help get this merged? Thanks!

**Review by swiatekm-sumo — APPROVED** [review]
I feel like there should be a way to do this without all the special cases, but we can refactor it later now that we have tests for them. I don't think there's any point in keeping this PR held up on DRY issues, so I'm approving it.

Thank you for the contribution!

**Comment by rashmichandrashekar** [comment]
Thanks @swiatekm-sumo! I dont have permissions to merge, could you pls merge this?
or maybe @jaronoff97 can help merge this?

**Review by jaronoff97 — APPROVED** [review]

**Pull request merged**
