### PR TITLE
Support for kubernetes 1.30 version

### PR DESCRIPTION
**Pull request by vasireddy99**
**Description:** Support for kubernetes 1.30 version

- Resolves: #2881

### CODE REVIEW

**Comment by pavolloffay** [comment]
Could you please change the version in the makefile https://github.com/open-telemetry/opentelemetry-operator/blob/0e96e1fb07e135c36321b996cdc75d85235e42d6/Makefile#L65

**Comment by vasireddy99** [comment]
> Could you please change the version in the makefile
> 
> https://github.com/open-telemetry/opentelemetry-operator/blob/0e96e1fb07e135c36321b996cdc75d85235e42d6/Makefile#L65

Thanks for pointing, updated the version

**Review by swiatekm-sumo — APPROVED** [review]

**Review by jaronoff97 — APPROVED** [review]
@pavolloffay do we need to upgrade the operator-sdk [references too](https://github.com/open-telemetry/opentelemetry-operator/blob/b461534020cee7503c5465193d68c4747b135d65/bundle/metadata/annotations.yaml#L8)?

**Comment by vasireddy99** [comment]
> @pavolloffay do we need to upgrade the operator-sdk [references too](https://github.com/open-telemetry/opentelemetry-operator/blob/b461534020cee7503c5465193d68c4747b135d65/bundle/metadata/annotations.yaml#L8)?

I created this [PR](https://github.com/open-telemetry/opentelemetry-operator/pull/2982) in case.

**Review by pavolloffay — APPROVED** [review]

**Pull request merged**
