### PR TITLE
Use unique label and selector for operator objects

### LINKED ISSUE #652: failed calling webhook "mopentelemetrycollector.kb.io"
full error message

```
Error from server (InternalError): error when creating "abc": Internal error occurred: failed calling webhook "mopentelemetrycollector.kb.io": failed to call webhook: Post "https://opentelemetry-operator-controller-manager-service.openshift-operators.svc:443/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector?timeout=10s": dial tcp 10.131.0.154:9443: connect: connection refused
```

Reason:
- Operator is installed in openshift-operators
- some other operators are installed in the same namespace, like kogito, gitops
- service "opentelemetry-operator-controller-manager-service" has as podselector defined "control-plane=controller-manager"
--> the service is also pointing to the wrong pods from the other operators...
Sometimes it does not work, sometimes it works, depended which pod the service is selecting!

```
$ oc get pod -l control-plane=controller-manager
NAME                                                         READY   STATUS    RESTARTS      AGE
gitops-operator-controller-manager-54d4756897-7gczv          1/1     Running   0             31h
kogito-operator-controller-manager-7d5fc8f765-kntnr          2/2     Running   4 (28h ago)   28h
opentelemetry-operator-controller-manager-69f7f56598-z8dck   2/2     Running   0             56m
```

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>

Resolves #652

Example objects.yaml: 
[out.txt](https://github.com/open-telemetry/opentelemetry-operator/files/8031610/out.txt)

### CODE REVIEW

**Comment by pavolloffay** [comment]
@rbaumgar could you please review?

**Review by jpkrohling — APPROVED** [review]
Should this be merged for 0.43.0, or should we wait for 0.44.0, which can be done right after 0.43.0?

**Comment by pavolloffay** [comment]
I don't have any preference, but it seems safe to get it merged

**Comment by jpkrohling** [comment]
@yuriolisa, given that there are changes requested in the PR preparing the 0.43 release, I'll merge this now. Please, include it in the changelog for 0.43.0.

**Comment by rbaumgar** [comment]
@jpkrohling looks good!
is the operator somehow based on the Operator SDK? If yes, shouldn't this be somehow feedback to the SDK team? Because this is not the first project having this problem.

**Pull request merged**
