### PR TITLE
chore: chainsaw improvements

### PR DESCRIPTION
**Pull request by eddycharly**
Chainsaw improvements (based on comments in #2630)
- simplified makefile
- used resource/namespace templating instead of `kubectl` commands

### CODE REVIEW

**Comment by eddycharly** [comment]
Things like this could probably be eliminated too
```

# Name of the daemonset to check
DAEMONSET_NAME="prometheus-kubernetessd-collector"

# Get the desired and ready pod counts for the daemonset
read DESIRED READY <<< $(kubectl get daemonset -n $NAMESPACE $DAEMONSET_NAME -o custom-columns=:status.desiredNumberScheduled,:status.numberReady --no-headers)

# Check if the desired count matches the ready count
if [ "$DESIRED" -eq "$READY" ]; then
  echo "Desired count ($DESIRED) matches the ready count ($READY) for $DAEMONSET_NAME."
else
  echo "Desired count ($DESIRED) does not match the ready count ($READY) for $DAEMONSET_NAME."
  exit 1
fi
```

**Comment by eddycharly** [comment]
Did i break a unit test ? 🤔

**Comment by swiatekm-sumo** [comment]
> Did i break a unit test ? 🤔

No, I'm fixing it here: https://github.com/open-telemetry/opentelemetry-operator/pull/2643. It does seem to break much more frequently here than in any other PR, which made it easier to hunt down.

**Review by swiatekm-sumo — APPROVED** [review]
Nice, this looks much better than before.

**Comment by eddycharly** [comment]
Honestly your tests are of good quality, I often see a lot of hacks to workaround kuttl limitations but not in your tests ! 💪

**Comment by eddycharly** [comment]
Like this one [Kuttl-In-Kuttl](https://github.com/linode/cluster-api-provider-linode/blob/main/e2e/README.MD) 😂 🙈

**Comment by swiatekm-sumo** [comment]
> Honestly your tests are of good quality, I often see a lot of hacks to workaround kuttl limitations but not in your tests ! 💪

Have you looked at the target allocator tests with jobs running curl in a loop to check if metrics are available? :see_no_evil:

**Comment by eddycharly** [comment]
> Have you looked at the target allocator tests with jobs running curl in a loop to check if metrics are available? 🙈

Not yet ! But metrics is an area we want to address, this is often not well end to end tested and chainsaw could easily be adapted to assert on metrics imho.

**Comment by eddycharly** [comment]
I will address this one next https://github.com/open-telemetry/opentelemetry-operator/blob/main/tests/e2e-targetallocator/targetallocator-kubernetessd/check-daemonset.sh

We really can do better than that !

**Review by jaronoff97 — APPROVED** [review]

**Pull request merged**
