### PR TITLE
test: use utilruntime package wrap AddToScheme method

### PR DESCRIPTION
**Pull request by googs1025**
**Description:** <Describe what has changed.>
Use utilruntime package wrap AddToScheme method

**Link to tracking Issue(s):** <Issue number if applicable>

- Resolves: #issue-number

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by swiatekm-sumo — APPROVED** [review]
Nice, thank you for your contribution!

**Comment by googs1025** [comment]
@swiatekm-sumo Thank you for your code review. If it can be merged, please help me merge it.

**Comment by swiatekm-sumo** [comment]
@googs1025 we still need maintainer approval. Unless they have any comments, this PR will be merged shortly afterwards.

**Review by jaronoff97 — APPROVED** [review]

**Comment by jaronoff97** [comment]
Thank you for your contribution!

**Pull request merged**
