### PR TITLE
config: update kustomization field names

### LINKED ISSUE #2100: `patchesStrategicMerge` is deprecated
Steps to reproduce:

1. Download repository
2. Execute `make test`

Output contains:
```log
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

### PR DESCRIPTION
**Pull request by frzifus**
Closes #2100

### CODE REVIEW

**Review by jaronoff97 — APPROVED** [review]

**Comment by jaronoff97** [comment]
looks like some tests are failing from this, do we need to upgrade the kustomize version somewhere?

**Comment by frzifus** [comment]
hm.. No clue, I used the current kustomize version to fix things. ^^
```bash
pushd config/crd && ../../bin/kustomize edit fix --vars && popd
pushd config/default && ../../bin/kustomize edit fix --vars && popd
```
But then the formatting was completely messed up and I changed a few things back by hand. Maybe thats the reason.

**Comment by frzifus** [comment]
I will check this tomorrow :X

**Comment by frzifus** [comment]
ok, my understanding is that the kustomize version is to new :no_good:  
- https://github.com/operator-framework/operator-sdk/issues/6531
- https://sdk.operatorframework.io/docs/upgrading-sdk-version/

**Pull request closed without merging**
