### PR TITLE
Test on Kubernetes 1.26

### LINKED ISSUE #1385: Test on Kuberentes 1.26.0
https://kubernetes.io/releases/#release-v1-26

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26

```
The autoscaling/v2beta2 API version of HorizontalPodAutoscaler is no longer served as of v1.26.

Migrate manifests and API clients to use the autoscaling/v2 API version, available since v1.23.
All existing persisted objects are accessible via the new API
```

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>

Resolves #1385

### CODE REVIEW

**Review by iblancasa — CHANGES_REQUESTED** [review]
The failure in teh `autoscale` E2E test, is fixed as part of #1365

**Review by iblancasa — CHANGES_REQUESTED** [review]
The unit tests depends on the KUBE_VERSION too

**Comment by pavolloffay** [comment]
> The unit tests depends on the KUBE_VERSION too

reverting back the default to 1.24 for the unit tests.

**Comment by iblancasa** [comment]
@pavolloffay could you re-run the E2E tests? It seems something didn´t work properly with GitHub Actions Workflows.

**Comment by pavolloffay** [comment]
> 
@pavolloffay could you re-run the E2E tests? It seems something didn´t work properly with GitHub Actions Workflows.

All tests passed but the e2e 1.25 job needs to be removed from the required actions.

**Comment by pavolloffay** [comment]
Asked for maintenance permissions https://github.com/open-telemetry/community/issues/1381

**Comment by arminru** [comment]
@pavolloffay I removed the 1.25 check and re-ran your tests so I can add 1.26 as required instead. You should already be able to merge the PR, however.

**Review by yuriolisa — APPROVED** [review]

**Pull request merged**
