### PR TITLE
[chore] prepare release 0.97.0

### PR DESCRIPTION
**Pull request by atsu85**
# Description:
I followed [RELEASE instructions](https://github.com/open-telemetry/opentelemetry-operator/blob/70d47d8e578fd36ff3f3a8caad5b777dfc8f8aad/RELEASE.md)

# Link to tracking Issue(s):

* Resolves: #2766 

# Notes
@jaronoff97, based on the [Release schedule](https://github.com/open-telemetry/opentelemetry-operator/blob/70d47d8e578fd36ff3f3a8caad5b777dfc8f8aad/RELEASE.md?plain=1#L47) it seems that you should be responsible for this release.

When trying to follow the [release instructions](https://github.com/open-telemetry/opentelemetry-operator/blob/70d47d8e578fd36ff3f3a8caad5b777dfc8f8aad/RELEASE.md?plain=1#L1-L22) I started questioning if i should even send the release PR myself, but I guess this PR shouldn't hurt.

I created separate commit for each step in the release instructions, so it might be easier to review my changes (i guess they will be squashed with the merge anyway)

# Testing

I'm not completely sure if regarding the last point regarding preparing the release:
> [Check the OpenTelemetry Collector's changelog and ensure migration steps are present in pkg/collector/upgrade](https://github.com/open-telemetry/opentelemetry-operator/blob/70d47d8e578fd36ff3f3a8caad5b777dfc8f8aad/RELEASE.md?plain=1#L17)

there should have been any changes - I didn't add any myself, but I'm not sure if smth should have been added.

### CODE REVIEW

**Comment by jaronoff97** [comment]
@atsu85 thanks for opening this! We need to wait on the collector release to merge and I'm not sure that will be this week given KubeCon EU is happening. Once the collectors release is complete I'd be happy to review and merge this!

**Comment by atsu85** [comment]
@jaronoff97 , thanks for quick reply.

> We need to wait on the collector release to merge


oh, i see i've bumped the collector version (that seems to be usually in sync with operator version) before it was released, and hence the e2e tests fail currently.

> ...and I'm not sure that will be this week

I'm wondering if it would be possible to release operator version without collector? I'm eager to start using it for lots of our projects.

If that would be an option, I guess i should revert most of [my changes in version.txt ](https://github.com/open-telemetry/opentelemetry-operator/pull/2767/commits/619fa2e7fe4a879af0c73585ddab223fc7b46224), besides autoinstrumentation-nodejs and operator?

**Comment by jaronoff97** [comment]
@atsu85 i don't think we will be cutting a new release just for this, unfortunately. We usually reserve patch releases for immediate fixes in the most recent release. In the meantime, you should be able to provide your own auto-instrumentation node image by setting the `auto-instrumentation-nodejs-image` argument for the operator. The version you would like to use already [has an image published](https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fautoinstrumentation-nodejs/190418842?tag=0.49.1).

**Comment by pavolloffay** [comment]
Agree with @jaronoff97. We should wait for the collector release. In the meantime the nodejs image can be overridden in the instrumentation CR or you can override the base auto-instrumentation image as a flag on the operator.

**Comment by atsu85** [comment]
> i don't think we will be cutting a new release just for this

yeah

> In the meantime, you should be able to provide your own auto-instrumentation node image by setting the auto-instrumentation-nodejs-image argument for the operator

actually i already found that before i noticed your answer (and how to [override it via opentelemetry-operator helm chart values](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/values.yaml#L46-L48))

**Pull request closed without merging**
