### PR TITLE
Release v0.49.0

### LINKED ISSUE #701: Change structure of our changelog to align with OTELcol core/contrib
Should we use the same changelog scheme of OTEL Core / Contrib?

### LINKED ISSUE #819: Release the operator v0.49.0

### PR DESCRIPTION
**Pull request by yuriolisa**
Signed-off-by: Yuri Sa <yurimsa@gmail.com>

Resolves #819 
Resolves #701

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Please nore 0.49.0 hasn't been released yet: https://github.com/open-telemetry/opentelemetry-collector-releases/releases

**Comment by dmitryax** [comment]
The release is currently blocked by https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9278

**Comment by dmitryax** [comment]
OTel col binaries are published now

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
@open-telemery/operator-maintainers can this be merged?

**Pull request merged**
