### PR TITLE
Fix getPrometheusExporterPorts incorrectly matching to prometheusremotewrite exporter (#2016)

### LINKED ISSUE #2016: When upgrading to v0.82.0, the collector cannot be created normally after adding prometheusremotewrite exporter
**helm chart version**
image

**command**
``` bash
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: demo
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:
      prometheusremotewrite/prometheus:
        endpoint: http://prometheus-server.monitoring/api/v1/write

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
EOF
```

**opentelemetry-operator log**
```
{"level":"error","ts":"2023-08-13T11:52:04Z","msg":"Reconciler error","controller":"opentelemetrycollector","controllerGroup":"opentelemetry.io","contro   llerKind":"OpenTelemetryCollector","OpenTelemetryCollector":{"name":"demo","namespace":"otel-system"},"namespace":"otel-system","name":"demo","reconcile   ID":"09ae9af8-47a2-4861-a8b7-cc84087a9906","error":"failed to reconcile the expected deployments: failed to create: Deployment.apps \"demo-collector\" i   s invalid: spec.template.spec.containers[0].ports[3].containerPort: Required value","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller   .(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-   runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controll   er.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/   internal/controller/controller.go:226"}
```

### PR DESCRIPTION
**Pull request by hzhhong**
fix #2016

### CODE REVIEW

**Review by iblancasa — APPROVED** [review]

**Comment by iblancasa** [comment]
Good catch! @hzhhong
Thanks for fixing :)

**Review by frzifus — APPROVED** [review]

**Review by swiatekm-sumo — APPROVED** [review]

**Comment by cmergenthaler** [comment]
Any chance to have a patch release for this as the 0.82.0 is broken when using prometheusremotewrite exporter?

**Comment by jaronoff97** [comment]
@cmergenthaler discussing this right now! Will get back to you soon.

**Comment by jaronoff97** [comment]
@cmergenthaler given we have a pending release https://github.com/open-telemetry/opentelemetry-operator/issues/2020 we're just going to get that released today.

**Pull request merged**
