### PR TITLE
Promote frzifus to maintainer

### PR DESCRIPTION
**Pull request by frzifus**
Hey, I would like formally request to be made an Maintainer for opentelemetry-operator.

### CODE REVIEW

**Comment by jaronoff97** [comment]
I support this! :bow: 🎉

**Review by jaronoff97 — APPROVED** [review]

**Review by swiatekm — APPROVED** [review]
Welcome to the jungle.

**Review by TylerHelmuth — APPROVED** [review]
🥳

**Comment by frzifus** [comment]
cc @pavolloffay :smiley:

**Comment by pavolloffay** [comment]
+1 sorry for joining late :)

**Review by pavolloffay — APPROVED** [review]

**Pull request merged**
