### PR TITLE
Add login step to publishing of images

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
Now it works:

image

**Comment by objectiser** [comment]
@jpkrohling  Just wondering whether we actually need the sha tag at the moment?

Would it also be worth changing master -> main before 1.x?

**Comment by jpkrohling** [comment]
We don't need the SHA. Using master here comes from the branch name, but it might indeed be a good idea to change it soon to avoid breaking users.

**Comment by jpkrohling** [comment]
#143 to track the branch rename

**Pull request merged**
