### PR TITLE
Publish operator images for IBM P/Z

### PR DESCRIPTION
**Pull request by pavolloffay**
The collector is published for IBM P/Z https://github.com/open-telemetry/opentelemetry-collector-releases/pkgs/container/opentelemetry-collector-releases%2Fopentelemetry-collector/136233520?tag=0.87.0

### CODE REVIEW

**Comment by swiatekm-sumo** [comment]
Is it actually possible to run Kubernetes on these architectures? If so, is anyone actually doing it and interested in running the otel operator? I'm asking because we don't have any straightforward way of validating these images.

**Comment by pavolloffay** [comment]
Yes, internally we run tests for these architectures

**Review by swiatekm-sumo — APPROVED** [review]

**Review by TylerHelmuth — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
1 think we might want to note is that the Go auto-instrumentation image is not built for those 2 architectures.

**Review by frzifus — APPROVED** [review]

**Review by iblancasa — APPROVED** [review]

**Comment by pavolloffay** [comment]
> 1 think we might want to note is that the Go auto-instrumentation image is not built for those 2 architectures.

@iblancasa is working on publishing the auto-instrumentation libs for different archs. Other langs might have a similar limitation (e.g. .net).

**Pull request merged**
