### PR TITLE
Default to UDP protocol for statsd receiver

### PR DESCRIPTION
**Pull request by PeterSzegedi**
The statsd receiver's service and deployment should default to UDP 8125 instead of the TCP 8125. 
Currently the collector pod/container is unreachable, when someone tries to spin up a statsd receiver because the pod is listening on the UDP port, but the service and the deployment is exposing TCP.
 
The TCP protocol has not been implemented for the statsd receiver, so having a default to TCP is not useful [link](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/statsdreceiver/receiver.go#L78)

I have built the controller image on my local minikube and it seems to fix the issue.

Let me know how, if any changes are needed to get this merged. 

Thanks,
Peter

### CODE REVIEW

**Review by matej-g — COMMENTED** [review]
Thanks for this @PeterSzegedi, I think it really should be UDP 👍.

You might need to sign the CLA in order to make CI run / green. Otherwise this looks good to me!

**Comment by PeterSzegedi** [comment]
Hi @matej-g ,
I am in the process of sorting the CLA. I will update the ticket when it is done

**Comment by PeterSzegedi** [comment]
Hi @matej-g ,
The CLA approval is fine now, but it seems the workflows need a maintainer to kick them off. Could you do the honours please?

Thanks,
Peter

**Comment by matej-g** [comment]
Hey, not a maintainer, but let's see if we can bother @pavolloffay or @frzifus 🙂

**Review by matej-g — APPROVED** [review]

**Review by frzifus — APPROVED** [review]
thanks for taking care @PeterSzegedi ! Could you please add a changelog entry? :)

**Comment by PeterSzegedi** [comment]
Thanks both :)
I have added an entry and an issue to provide the issue number in the changelog. https://github.com/open-telemetry/opentelemetry-operator/issues/1476

**Comment by PeterSzegedi** [comment]
Ah, apologies, forgot to make it yaml. I will fix it now

**Comment by frzifus** [comment]
Sure :)

**Review by pavolloffay — APPROVED** [review]

**Pull request merged**
