### PR TITLE
OTEL Operator release 0.51.0

### LINKED ISSUE #868: Release the operator v0.51.0

### PR DESCRIPTION
**Pull request by erichsueh3**
Resolves #868 for operator release 0.51.0

### CODE REVIEW

**Comment by erichsueh3** [comment]
Couple of notes:
1. Is the lower bound on k8s supported versions now N-4 instead of N-2? If so, I can change that in `RELEASE.md`
2. While on the topic of k8s versions, should the range actually be 1.20-1.24 now? [1.24](https://github.com/kubernetes/kubernetes/releases/tag/v1.24.0) was released 9 days ago, but 0.50 of the Operator release was 3 days ago and supports 1.19-1.23. If yes, then I can make the changes so the e2e and scorecard tests are for updated versions, as well as updating the versions on the README

**Comment by mat-rumian** [comment]
Could we please release with this fix https://github.com/open-telemetry/opentelemetry-operator/pull/864?

**Comment by pavolloffay** [comment]
> Is the lower bound on k8s supported versions now N-4 instead of N-2? If so, I can change that in RELEASE.md 

https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-operator-vs-kubernetes-vs-cert-manager

> We strive to be compatible with the widest range of Kubernetes versions as possible, but some changes to Kubernetes itself require us to break compatibility with older Kubernetes versions, be it because of code incompatibilities, or in the name of maintainability. Every released operator will support a specific range of Kubernetes versions, to be determined at the latest during the release.

And https://github.com/open-telemetry/opentelemetry-operator/blob/main/.github/workflows/e2e.yaml#L15

Essentially we (community/maintainers) decide which versions of k8s are supported. There is not strict policy on N-X.

**Comment by pavolloffay** [comment]
> While on the topic of k8s versions, should the range actually be 1.20-1.24 now? [1.24](https://github.com/kubernetes/kubernetes/releases/tag/v1.24.0) was released 9 days ago, but 0.50 of the Operator release was 3 days ago and supports 1.19-1.23. If yes, then I can make the changes so the e2e and scorecard tests are for updated versions, as well as updating the versions on the README

Feel free to add support for 1.24 in a separate PR.

**Review by pavolloffay — APPROVED** [review]

**Comment by pavolloffay** [comment]
@erichsueh3 please include https://github.com/open-telemetry/opentelemetry-operator/pull/864 in the changelog.

**Comment by pavolloffay** [comment]
Also include https://github.com/open-telemetry/opentelemetry-operator/pull/689 in the changelog

**Comment by erichsueh3** [comment]
Updated the changelog @pavolloffay @mat-rumian

**Comment by erichsueh3** [comment]
Can we re run the 1.19 e2e tests?

**Comment by bogdandrutu** [comment]
@erichsueh3 triggered the "re-run"

**Comment by pavolloffay** [comment]
@erichsueh3 please rebase the PR and the CI should pass.

**Comment by erichsueh3** [comment]
@pavolloffay rebased and now 1.19 tests pass but 1.23 tests fail, not sure why

**Comment by pavolloffay** [comment]
I have just re-run the tests. Did you re-run as well?

**Comment by pavolloffay** [comment]
passed, it was probably a flaky test

**Pull request merged**
