### PR TITLE
Update comments to reflect correct name of component

### PR DESCRIPTION
**Pull request by alexperez52**
## Description
Updated comments in 2 files to represent the correct name of component. Load balancer -> Target Allocator
This closes [#903](https://github.com/open-telemetry/opentelemetry-operator/issues/903)

### CODE REVIEW

**Review by pavolloffay — APPROVED** [review]

**Comment by alexperez52** [comment]
Hi @pavolloffay ! Could this be merged ?

**Comment by pavolloffay** [comment]
@alexperez52 CI failed and there is no way to restart it - at least I don't see that option in GHA action.

could you please rebase the PR? It will trigger the CI again.

**Comment by frzifus** [comment]
I assume clicking on `update branch` should be enough. @alexperez52 or @pavolloffay

**Review by frzifus — APPROVED** [review]

**Comment by jaronoff97** [comment]
We've moved some files around but this is still a problem, I'll open up a fix

**Pull request closed without merging**
