### PR TITLE
Add logging for prometheus operator in TargetAllocator's config generator

### PR DESCRIPTION
**Pull request by rashmichandrashekar**
**Description:** 
Adding a feature - Currently, the prometheus operator logs, if any, are not visible from the targetallocator. This change enables error logging from prometheus-operator

**Testing:** Tested that logs that are returned by prometheus operator are logged to stdout

Sample logs - 

image

### CODE REVIEW

**Review by jaronoff97 — APPROVED** [review]

**Comment by jaronoff97** [comment]
How busy were the logs when you enabled this? could you add some samples ones to the PR description?

**Comment by rashmichandrashekar** [comment]
> How busy were the logs when you enabled this? could you add some samples ones to the PR description?

Thanks @jaronoff97. The logs were not busy. Since it is mostly only for invalid cases like the one in the description.

**Review by frzifus — APPROVED** [review]

**Comment by rashmichandrashekar** [comment]
@jaronoff97 @frzifus - Please help get this merged, as I dont have permissions. Thanks!

**Comment by frzifus** [comment]
LGTM @jaronoff97 has to click :)

**Comment by jaronoff97** [comment]
Sorry I am on PTO today, but can merge real quick :)

**Comment by rashmichandrashekar** [comment]
> Sorry I am on PTO today, but can merge real quick :)

Thanks so much @jaronoff97!

**Pull request merged**
