### PR TITLE
Release v0.69.0

### LINKED ISSUE #1356: Release the operator v0.69.0

### PR DESCRIPTION
**Pull request by yuriolisa**
Signed-off-by: Yuri Sa <yurimsa@gmail.com>
Resolves #1356

### CODE REVIEW

**Review by frzifus — COMMENTED** [review]
I assume we need to delete all the old changelog (`.chloggen`) files, right?

**Comment by yuriolisa** [comment]
@frzifus, I've removed all the old chlog files, but when I ran the `make chlog-update` I'm getting the following message: 
`Error: no entries to add to the changelog`.

**Comment by bryan-aguilar** [comment]
Can we ensure that #1450 gets merged before `v0.69.0` is released?

**Comment by matej-g** [comment]
If https://github.com/open-telemetry/opentelemetry-operator/pull/1383 is in, then I think it would be good idea to also include https://github.com/open-telemetry/opentelemetry-operator/pull/1414 in the release, as without it the current HTTP server config is not ideal and rather noisy.

**Comment by pavolloffay** [comment]
@yuriolisa #1414 was merged. Could you please re-generate the changelog?

**Review by pavolloffay — APPROVED** [review]

**Pull request merged**
