### PR TITLE
fix for #2366

### LINKED ISSUE #2366: Nginx autoinstrument fails for nginx-ingress pod
### Component(s)

instrumentation

## Description
When using nginx auto-instrumentation with nginx, pods fail to create with this error:
```
conditions:
  - lastTransitionTime: "2023-11-16T19:59:24Z"
    message: 'Pod "ingress-nginx-internal-controller-5f98f56d9d-w8k4k" is invalid:
      spec.initContainers[0].lifecycle: Forbidden: may not be set for init containers'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
```

Seems this issue may be related to another issue previously reported: https://github.com/open-telemetry/opentelemetry-operator/issues/1820 

## Steps to Reproduce
- opentelemetry-operator helm chart 0.41.0
- Add `instrumentation.opentelemetry.io/inject-nginx: monitoring/demo-nginx-instrumentation` to the nginx ingress helm chart 

## Expected Result
Auto-instrumentation works

## Actual Result
Fails with above error.

### Kubernetes Version

1.26.3

### Operator version

0.41.0

### Collector version

NA

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chrlic**
**Description:** Fix for

Resolves #2366 - removal of lifecycle on cloned initContainer

**Link to tracking Issue:** #2366

**Testing:** Added test case to verify lifecycle removal from clonedInit container

**Documentation:** N/A

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
I can review when I'm back on Monday.

**Review by swiatekm-sumo — COMMENTED** [review]
The fix looks fine to me. Can we also set the lifecycle on the nginx Pod in the E2E test for this instrumentation? I think that would be here: https://github.com/open-telemetry/opentelemetry-operator/blob/main/tests/e2e-instrumentation/instrumentation-nginx-contnr-secctx/01-install-app.yaml.

**Comment by chrlic** [comment]
Sure, I'm out till Monday, this was max I dared to do remote.


Dne čt 23. 11. 2023 11:50 uživatel Mikołaj Świątek ***@***.***>
napsal:

**Comment by swiatekm-sumo** [comment]
I don't think we need a separate E2E test for this, I'd just like to have it set in one of the existing ones as a smoke detector.

**Review by pavolloffay — APPROVED** [review]

**Comment by pavolloffay** [comment]
It will be included in 0.90.0 release. We release the operator once OTEL collector is released. The release usually happens quite often.

**Comment by djluck** [comment]
@pavolloffay would it be possible to release a new version now?

**Comment by pavolloffay** [comment]
This patch should have been released a long time ago

**Comment by djluck** [comment]
Apologies, I was looking in the wrong place 🤦 

Thanks guys for your work in fixing this 👍

**Pull request merged**
