### PR TITLE
Bump base memory requirements for python and go

### PR DESCRIPTION
**Pull request by jcreixell**
**Description:** <Describe what has changed.>
  - When auto-instrumenting applications, I have noticed that default memory limits are too tight for some languages. This leads to the following:
    - Intermitent OOMKilled events in init container when auto-instrumenting python applications. Eventually the pods are able to start.
    - OOMKilled events for sidecar containers in go applications. The pods are not able to start.
  - 64Mi seems to be enough to fix these issues. While some tweaking by users may still be necessary, the operator should work out-of-the-box for all supported languages.

**Link to tracking Issue(s):**
https://github.com/open-telemetry/opentelemetry-operator/issues/3479

### CODE REVIEW

**Review by iblancasa — COMMENTED** [review]
Please, add a changelog

**Comment by swiatekm** [comment]
Can you reproduce the OOMKills in a kind cluster? I'm not against bumping the requirements, but I don't understand why these containers would need it. The only thing they actually do is copy some files over to a shared volume.

**Comment by jcreixell** [comment]
I am able to consistently reproduce the go OOMs with both k3d and kind:

kind

Interestingly, the python OOMs only happen with k3d, not kind.

Screenshot from 2024-11-20 18-33-10

Screenshot from 2024-11-20 18-33-55

I am using a standard setup following the README. For testing, I use the rolldice applications with their manual instrumentation code stripped out.

(I will move this to an issue and link it in the changelog)

**Review by iblancasa — APPROVED** [review]

**Review by swiatekm — APPROVED** [review]
This looks good to me, and I'm fine merging it as-is. But I'd like to understand why our e2e tests don't catch it, and ideally modify them to do so. @jcreixell could you open a follow-up issue to track that?

**Comment by jcreixell** [comment]
@swiatekm  sure, there we go https://github.com/open-telemetry/opentelemetry-operator/issues/3484

**Pull request merged**
