### PR TITLE
Change GHCR bundle image to fix publish issues

### PR DESCRIPTION
**Pull request by pavolloffay**
Updates https://github.com/open-telemetry/opentelemetry-operator/issues/2001

### CODE REVIEW

**Review by jaronoff97 — APPROVED** [review]

**Comment by pavolloffay** [comment]
Skipping the changelog, image has never been published

**Comment by swiatekm-sumo** [comment]
Why should this help at all?

**Comment by pavolloffay** [comment]
> Why should this help at all? 

TBH I am not sure. The test e2e images were published without issues, so maybe changing the name will help

**Comment by jaronoff97** [comment]
🤞

**Pull request merged**
