### PR TITLE
Add Operator-Opamp-Bridge build and version info to Operator

### PR DESCRIPTION
**Pull request by avadhut123pisal**
Signed-off-by: Avadhut Pisal <avadhutpisal47@gmail.com>

This PR is raised as per the comment: https://github.com/open-telemetry/opentelemetry-operator/pull/1455#issuecomment-1420956070

### CODE REVIEW

**Comment by avadhut123pisal** [comment]
@jaronoff97  Please review.

**Review by jaronoff97 — COMMENTED** [review]
This looks good to me!
Two things before this can be merged:
* How was this tested?
* Could you add a changelog for this enhancement :D

Thank you!

**Comment by avadhut123pisal** [comment]
> This looks good to me! Two things before this can be merged:
> 
> * How was this tested?
> * Could you add a changelog for this enhancement :D
> 
> Thank you!

* How was this tested?

This change doesn't involve any functional change. For testing, I created a build of the Operator and in the Operator logs verified the build information, there I can see the OpAMP bridge version.

* Could you add a changelog for this enhancement
  Done.

**Comment by jaronoff97** [comment]
Perfect, just wanted to check that a build was attempted and run and that you observed the expected opamp-bridge info. Thank you!

**Review by jaronoff97 — APPROVED** [review]

**Pull request merged**
