### PR TITLE
Add nodejs auto-instrumentation support for linux/s390x,linux/ppc64le

### PR DESCRIPTION
**Pull request by pavolloffay**
**Description:** <Describe what has changed.>

**Link to tracking Issue(s):** <Issue number if applicable>

- Resolves: #3322 

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by swiatekm — COMMENTED** [review]
Have you tested that this actually works? It does appear to build correctly.

**Comment by pavolloffay** [comment]
no, this was best effort :)

**Comment by swiatekm** [comment]
Putting aside Kubernetes, are we even sure the JS instrumentation supports these architectures?

Or, to put it a different way, why make this change at all?

**Comment by pavolloffay** [comment]
@IshwarKanse will look into testing this

**Comment by pavolloffay** [comment]
There are some references so hopefully it works https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-js%20s390x&type=code. nodejs should be cross platform

**Review by iblancasa — APPROVED** [review]

**Review by frzifus — APPROVED** [review]

**Comment by IshwarKanse** [comment]
Working on this to verify on the IBM platforms today.

**Pull request merged**
