### PR TITLE
Move all approvers to emeritus, remove inheritance from collector-approver

### PR DESCRIPTION
**Pull request by bogdandrutu**
/cc @Aneurysm9 @dmitryax @jrcamp @james-bebbington @owais @mx-psi if you want to be kept as an "active approver" say something in this PR.

A separate PR will be done for maintainers.

### CODE REVIEW

**Comment by dmitryax** [comment]
I'll stay in approver role, can help with reviewing PRs

**Comment by alolita** [comment]
I'd like to be a reviewer. Also, @erichsueh3 from my team is also actively helping with releases. 

What are the next steps @jpkrohling @pavolloffay

**Comment by bogdandrutu** [comment]
@alolita let's try to keep this PR only for existing approvers who were there only because they were part of the collector approvers. For new request consider to open a separate issue

**Comment by mx-psi** [comment]
I don't have any experience with the operator, so I would rather stay out for now, thanks for the ping!

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
> What are the next steps @jpkrohling @pavolloffay

I'm glad to answer your questions on another issue, but in short: the process is the same as the collector, and as soon as @erichsueh3 thinks he's ready to become an approver, we'll review the application and act accordingly. Right now, I don't think he has all the required contributions in place to be an approver.

**Comment by owais** [comment]
LGTM

**Comment by bogdandrutu** [comment]
I will merge this, @Aneurysm9 if you want to be active approver, feel free to create a PR and move you.

**Pull request merged**
