### PR TITLE
Remove TargetAllocator resource defaults

### PR DESCRIPTION
**Pull request by PeterSzegedi**
Hi all,

This is a small PR to fix https://github.com/open-telemetry/opentelemetry-operator/issues/1914
If you would prefer the other way around and to set defaults to the collector, let me know. Although I think having no default requests/limits makes more sense IMHO.

### CODE REVIEW

**Review by jaronoff97 — APPROVED** [review]
@yuriolisa this is going to revert part of your previous PR #1739 is that okay?

**Review by swiatekm-sumo — APPROVED** [review]
Conceptually, this looks good to me.

**Comment by jaronoff97** [comment]
+1 to what @swiatekm-sumo , @PeterSzegedi if you could update the changelog that would be great!

**Comment by PeterSzegedi** [comment]
Apologies for the slow response, I blame the summer.
I have added a subtext to give a heads up about the change.

**Review by jaronoff97 — APPROVED** [review]

**Comment by jaronoff97** [comment]
no problem, thank you very much!

**Pull request merged**
