### PR TITLE
add shareProcessNamespace capability to v1alpha2

### PR DESCRIPTION
**Pull request by frzifus**
**Description:** <Describe what has changed.>

**Link to tracking Issue:** <Issue number if applicable>

Closes https://github.com/open-telemetry/opentelemetry-operator/issues/2540

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by jaronoff97 — COMMENTED** [review]
need to run make generate

**Comment by frzifus** [comment]
afaik we do not generate `v1alpha2`, right?

**Comment by swiatekm-sumo** [comment]
> afaik we do not generate `v1alpha2`, right?

We don't build manifests, but we do generate the deepcopy code.

**Comment by frzifus** [comment]
Is coping a primitive values not covered in line 600? Since `make generate` does not produce any output. While when I change the field to be a ptr, I can see that the generator adds a few lines to copy the value. Once I change it back and run `make generate` it gets removed. :racehorse: 
https://github.com/open-telemetry/opentelemetry-operator/blob/e2773befed10dc6388a887229e35c673b60c883b/apis/v1alpha2/zz_generated.deepcopy.go#L598-L600

**Comment by swiatekm-sumo** [comment]
I was confused why the documentation change was in this PR, but it looks like it's because the original PRs didn't include it. Which is strange, because the CI should fail that. I'll look into it, but this PR seems fine even though the changes are confusing.

**Review by swiatekm-sumo — APPROVED** [review]

**Comment by frzifus** [comment]
Oh, I thought the generated lines belong to `v1alpha2`. But It seems that not part of `api.md` :rabbit: :facepalm:

**Review by pavolloffay — APPROVED** [review]

**Pull request merged**
