### PR TITLE
[Chore] Run all instrumentation tests with multi-instrumentation flag added.

### PR DESCRIPTION
**Pull request by IshwarKanse**
**Description:** <Describe what has changed.>

With changes in PR https://github.com/open-telemetry/opentelemetry-operator/pull/3213 we should run all the instrumentation tests with mulit-instrumenation flag added. 

**Testing:** <Describe what testing was performed and which tests were added.>
Tested the PR on OpenShift 4.16 cluster.

### CODE REVIEW

**Review by iblancasa — APPROVED** [review]

**Comment by iblancasa** [comment]
Related #3090

**Review by swiatekm — COMMENTED** [review]
Is the plan to move this flag to Beta (which enables it by default)? I'm not comfortable having no tests for the default flag values.

**Comment by IshwarKanse** [comment]
@swiatekm @iblancasa I can update this PR once https://github.com/open-telemetry/opentelemetry-operator/pull/3302 merges which enables the flag by default.

**Comment by iblancasa** [comment]
I included this changes in https://github.com/open-telemetry/opentelemetry-operator/pull/3302

**Comment by IshwarKanse** [comment]
Closing this one out as the commit is added as part of https://github.com/open-telemetry/opentelemetry-operator/pull/3302

**Pull request closed without merging**
