### PR TITLE
Add package godoc from CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by IanvsPoplicola**
This PR is for issue https://github.com/open-telemetry/opentelemetry-operator/issues/104

Add the package descriptions from [CONTRIBUTING.md](https://github.com/open-telemetry/opentelemetry-operator/blob/master/CONTRIBUTING.md) to the per-package godoc.

Some packages do not contain any Go files, so they are not modified in this PR.

### CODE REVIEW

**Review by jpkrohling — COMMENTED** [review]
Looks great! I would only ask for two minor things:

1. periods at the end of the sentences, as I think that's the convention for godoc
1. remove the (now) duplicate content from the contributing.md, perhaps pointing people to the godoc (http://localhost:6060/pkg/github.com/open-telemetry/opentelemetry-operator/ , or a hosted one, like https://godoc.org/).

**Comment by IanvsPoplicola** [comment]
Thank you for the review @jpkrohling! I've updated the godoc formatting.

As for removing the package info in `CONTRIBUTING.md`, some of the packages (the ones commented below) don't contain any Go files, so they cannot have package godoc. Do you think it might be better to keep everything in `CONTRIBUTING.md` for now?
```
├── api               # has no godoc
│   └── v1alpha1
├── build             # has no godoc
├── config
│   ├── certmanager   # has no godoc
│   ├── crd           # has no godoc
│   │   ├── bases     # has no godoc
│   │   └── patches   # has no godoc
│   ├── default       # has no godoc
│   ├── manager       # has no godoc
│   ├── manifests     # has no godoc
│   │   └── bases
│   ├── prometheus    # has no godoc
│   ├── rbac          # has no godoc
│   ├── samples       # has no godoc
│   └── webhook       # has no godoc
├── controllers
├── hack              # has no godoc
├── internal          # has no godoc
│   ├── config        # has no godoc
│   ├── podinjector
│   └── version
├── local             # has no godoc
└── pkg               # has no godoc
├── autodetect
├── collector
│   ├── adapters
│   ├── parser
│   ├── reconcile
│   └── upgrade
├── naming
├── platform
└── sidecar
```

**Comment by jpkrohling** [comment]
We can ignore most of them, except for what's in `config`. I think it would then make sense to create a new README.md for the `config`, where the contents of the child directories are explained. I don't think they'll change as often as the Go packages, which was the main concern driving this issue.

**Comment by IanvsPoplicola** [comment]
Sounds good, I've made the changes now

**Review by jpkrohling — APPROVED** [review]
LGTM. Thanks for your contribution!

**Pull request merged**
