### PR TITLE
Update to collector v0.24.0

### LINKED ISSUE #238: Update to collector v0.24.0
Same as #231, but for 0.24.0. Changelog: https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.24.0

### PR DESCRIPTION
**Pull request by jnodorp-jaconi**
Fixes #238

### CODE REVIEW

**Comment by jpkrohling** [comment]
As discussed in the linked issue, I believe we need a small upgrade routine here.

**Review by jpkrohling — APPROVED** [review]
Looks awesome! Thanks!

**Comment by jnodorp-jaconi** [comment]
> Looks awesome! Thanks!

That was fast, thanks! Mind to tag a release?

**Comment by jnodorp-jaconi** [comment]
> Release triggered. I just realized that there's an entry missing in the changelog, #248. Would you mind sending a PR fixing the changelog?

Thank you! You tagged 0.25.0, though. Did you skip the 0.24.0 intentionally?

There you go: https://github.com/open-telemetry/opentelemetry-operator/pull/253

**Comment by jpkrohling** [comment]
No, it was not on purpose. I did a release of the builder at the same time and ended up using the same version. I just removed the release, the tag, and triggered a new one for 0.24.0. Thanks for bringing this to my attention!

**Pull request merged**
