### PR TITLE
[target-allocator] Use `gin` in release mode and without default logger middleware

### PR DESCRIPTION
**Pull request by matej-g**
Signed-off-by: Matej Gera <matej.gera@coralogix.com>

This is a follow-up to #1383.

This PR changes the `gin` router configuration to be suitable for production use, namely:
- It sets `gin` to be used in `release` mode (to my surprise, the default was `debug`)
- it opts out of using the default logger middleware. The logging seems rather verbose (logging each request) and the middleware is not using logging format that is consistent with logging format of the rest of the components in `target-allocator`. 

Eventually, it would be nice if we introduced our own logging middleware with formatting consistent with other components, but for now the default one seems noisy and not too useful to me.

cc @kristinapathak

### CODE REVIEW

**Review by frzifus — APPROVED** [review]

**Comment by matej-g** [comment]
Is the issue number mandatory in changelog? 🤔

**Comment by frzifus** [comment]
> Is the issue number mandatory in changelog? thinking

yes :D

**Comment by matej-g** [comment]
I did not create one but I guess it still should be part of #1352, so linking it to that one. Thanks @frzifus 😊.

**Comment by frzifus** [comment]
makes sense to me :)

**Review by jaronoff97 — APPROVED** [review]

**Review by yuriolisa — APPROVED** [review]

**Review by pavolloffay — APPROVED** [review]

**Pull request merged**
