### PR TITLE
Add basic instrumentation status condition

### PR DESCRIPTION
**Pull request by damemi**
Ref #1142 

This adds a basic `status` field to the Instrumentation crd based on the upstream [`Condition`](https://github.com/kubernetes/apimachinery/blob/d4f471b82f0a17cda946aeba446770563f92114d/pkg/apis/meta/v1/types.go#L1368) type.

Right now this just defines a single `Ready` status that defaults to false when the webhook catches a new pod. As the relevant agents are processed, the "Reason" identifies the last agent (ie `Reason: NodeAgent`). If the agent is injected successfully, the status becomes true.

This produces successful output like this:

```
$ kubectl get -o yaml instrumentation/my-instrumentation
...
status:
  conditions:
  - lastTransitionTime: "2022-11-07T19:46:58Z"
    message: ""
    reason: JavaAgent
    status: "True"
    type: Ready
```

and failures like this
```
$ kubectl get -o yaml instrumentation/my-instrumentation
...
status:
  conditions:
  - lastTransitionTime: "2022-11-07T19:44:44Z"
    message: 'the container defines env var value via ValueFrom, envVar: JAVA_TOOL_OPTIONS'
    reason: JavaAgent
    status: "False"
    type: Ready
```

Note this status will be overwritten by the next pod the operator attempts to process, so errors may be missed if the CR isn't being actively monitored for changes.

This also adds fields to track which containers have succeeded or failed, by language:
```
$ kubectl get -o yaml instrumentation/my-instrumentation
...
status:
  conditions:
  ...
  failed:
    java:
    - default/javashowcase-service
  succeeded:
    java:
    - default/javashowcase-app
    nodejs:
    - default/nodeshowcase-app
    - default/nodeshowcase-service
```

Unfortunately not all requests will have a pod name/namespace, so this is limited to the container name (which has the obvious risk of duplicates). Not sure how to handle that, but I'm open to ideas. Also open to suggestions on formatting/naming/general approach to either of these.

### CODE REVIEW

**Comment by pavolloffay** [comment]
> Note this status will be overwritten by the next pod the operator attempts to process, so errors may be missed if the CR isn't being actively monitored for changes.

If the status is overridden it does not seem useful to me. I would prefer to have an entry per injection in the status.

**Comment by damemi** [comment]
> If the status is overridden it does not seem useful to me.

Yeah, ideally it would know the state of all instrumented pods and report a single persistent "Degraded" status if any are actively failing to roll out (with more info in the reason/message). But as an admission webhook, that's not really doable because the logic is focused more on the individual pod than the overall state of the CRD. Maybe with an `Instrumentation` controller we could do something like that.

> I would prefer to have an entry per injection in the status.

Do you mean the `succeeded`/`failed` fields I added?

**Comment by yuriolisa** [comment]
@damemi, are you willing to continue working on it?

**Comment by jaronoff97** [comment]
@damemi wanted to check in again and see if you were interested in working on this? this would be really appreciated!

**Pull request closed without merging**
