### PR TITLE
fix: example for labels-filter startup parameter --label

### PR DESCRIPTION
**Pull request by chinaran**
**Description:** The labels-filter startup parameter, flag is --label, which is inconsistent with the example and variable name.

**Link to tracking Issue(s):** <Issue number if applicable>

- Resolves: #3201

### CODE REVIEW

**Review by iblancasa — CHANGES_REQUESTED** [review]
This can be a breaking change for those using the current value. We should change the example, not the flag

**Comment by pavolloffay** [comment]
+1 on aligning the example with the flag

**Comment by chinaran** [comment]
@iblancasa @pavolloffay 
Modifying flag directly does cause breaking changes, so I modified the example now.
There are just some inconsistencies between flag and expressed functions, especially when compared with the `--annotations-filter` flag.

**Comment by chinaran** [comment]
@iblancasa @pavolloffay
Additionally, there is currently a unit testing issue and I've also submitted a PR: https://github.com/open-telemetry/opentelemetry-operator/pull/3207

**Review by iblancasa — APPROVED** [review]

**Review by yuriolisa — APPROVED** [review]

**Review by jaronoff97 — APPROVED** [review]
This is fine for now, though I feel like we should align the naming in the future.

**Pull request merged**
