### PR TITLE
Make scorecard tests more reliable

### LINKED ISSUE #626: Flaky tests -- scorecard
The scorecard tests are failing intermittently. Examples:

https://github.com/open-telemetry/opentelemetry-operator/runs/4484687728?check_suite_focus=true
https://github.com/open-telemetry/opentelemetry-operator/actions/runs/1563783393/attempts/2

Following the OpenTelemetry Collector Contrib practices, the test will be disabled soon if it's not made stable.

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>

Resolves #626

### CODE REVIEW

**Comment by pavolloffay** [comment]
The unit tests failed on https://github.com/open-telemetry/opentelemetry-operator/issues/629

**Review by VineethReddy02 — APPROVED** [review]
LGTM! Let's get this merged once #630 gets in for the CI to pass.

**Comment by jpkrohling** [comment]
#630 is fixed, this needs a rebase to pick that fix.

**Pull request merged**
