### PR TITLE
add labels in order to make selectors unique

### LINKED ISSUE #791: label selectors on webhook service are not unique
```
k -n openshift-operators get svc  opentelemetry-operator-controller-manager-service  -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-03-21T13:51:59Z"
  labels:
    operators.coreos.com/opentelemetry-product.openshift-operators: ""
  name: opentelemetry-operator-controller-manager-service
  namespace: openshift-operators
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: ClusterServiceVersion
    name: opentelemetry-operator.v0.42.0
    uid: 1e5ba18c-7f48-4bd7-a944-0f48b43a00b7
  resourceVersion: "2222336329"
  uid: f89e5836-cb90-4e40-970f-92193c841952
spec:
  clusterIP: 10.201.121.49
  clusterIPs:
  - 10.201.121.49
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```

but other pods have same labels:
```
k -n openshift-operators get pod -l control-plane=controller-manager
NAME                                                         READY   STATUS    RESTARTS   AGE
gitops-operator-controller-manager-575b4c6568-4n29x          1/1     Running   0          11d
opentelemetry-operator-controller-manager-5cd67df476-tkc7t   2/2     Running   0          4h39m
```

so you end up with an error from the webhook when applying a resource:

```
k apply -f collector.yaml 
Error from server (InternalError): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"opentelemetry.io/v1alpha1\",\"kind\":\"OpenTelemetryCollector\",\"metadata\":{\"annotations\":{},\"name\":\"default\",\"namespace\":\"jaeger-system\"},\"spec\":{\"config\":\"receivers:\\n  otlp:\\n    protocols:\\n      grpc:\\n      http:\\nprocessors:\\nexporters:\\n  jaeger:\\n    endpoint: jaeger-default-collector-headless.jaeger-system.svc:14250\\n    tls:\\n      ca_file: \\\"/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt\\\"\\nservice:\\n  pipelines:\\n    traces:\\n      receivers: [otlp]\\n      processors: []\\n      exporters: [jaeger]\\n\",\"mode\":\"sidecar\"}}\n"}},"spec":{"mode":"sidecar"}}
to:
Resource: "opentelemetry.io/v1alpha1, Resource=opentelemetrycollectors", GroupVersionKind: "opentelemetry.io/v1alpha1, Kind=OpenTelemetryCollector"
Name: "default", Namespace: "jaeger-system"
for: "collector.yaml": Internal error occurred: failed calling webhook "mopentelemetrycollector.kb.io": failed to call webhook: Post "https://opentelemetry-operator-controller-manager-service.openshift-operators.svc:443/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector?timeout=10s": dial tcp 10.200.6.63:9443: connect: connection refused
```

### PR DESCRIPTION
**Pull request by davidkarlsen**
Fixes #791.

Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]

**Comment by davidkarlsen** [comment]
@jpkrohling when will a new release be cut - and do you know how much redhats fork lags behind?

**Comment by jpkrohling** [comment]
We release the operator typically following a collector release. There was one last week, so, next week should be a new one.

**Comment by jpkrohling** [comment]
About Red Hat versions, @pavolloffay can probably help you there.

**Comment by davidkarlsen** [comment]
ping @pavolloffay

**Pull request merged**
