### PR TITLE
Enabling kind version 1.22.4

### PR DESCRIPTION
**Pull request by yuriolisa**
Enabling kind version 1.22.4

### CODE REVIEW

**Comment by yuriolisa** [comment]
@jpkrohling

**Comment by jpkrohling** [comment]
The tests for 1.22 failed, I restarted, but it failed again. Did it work when you ran it locally?

**Comment by yuriolisa** [comment]
@jpkrohling , could you please re-check ?

**Comment by jpkrohling** [comment]
1.20 failed, re-running

**Comment by yuriolisa** [comment]
Now, all checks are ok. @jpkrohling

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
