### PR TITLE
Allow running daemonset in hostNetwork mode

### PR DESCRIPTION
**Pull request by owais**

### CODE REVIEW

**Comment by owais** [comment]
I believe this is all that is required to enable the feature to submitting for review but haven't yet tested locally in a real cluster yet. Will do that later today in a few hours and report back.

**Review by dmitryax — APPROVED** [review]

**Comment by owais** [comment]
Verified on a local cluster. Good to go.

**Review by dmitryax — APPROVED** [review]

**Review by jpkrohling — COMMENTED** [review]
Can you add an e2e test for this case? I know that some platforms like OpenShift restrict options like these, and an e2e test would be useful to validate that.

**Comment by owais** [comment]
@jpkrohling added e2e test for daemonset+hostNetwork

**Comment by VineethReddy02** [comment]
LGTM!

**Comment by owais** [comment]
@VineethReddy02 yeah these seem to be flaky tests. They fail randomly locally as well as on CI. I'm re-running the CI. Hopefully should be green in a few attempts.

**Comment by owais** [comment]
All green now @VineethReddy02 Thanks for the review.

**Review by dmitryax — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
