### PR TITLE
Upgrade controller-gen to v0.4.0 and change CRDs apiVersion to v1

### PR DESCRIPTION
**Pull request by bhiravabhatla**
Signed-off-by: santosh <bsantosh@thoughtworks.com>

Change Description

- Upgrade controller-gen version to v0.4.0. It by default creates CRDs using apiVersion apiextensions.k8s.io/v1
- Fix webhook patches to work with apiextensions.k8s.io/v1

### CODE REVIEW

**Comment by bhiravabhatla** [comment]
Need to move webhook manifests to v1 as well. For that would need to confirm, if I can mark sideAffects as None. SideAffects is a mandatory field in v1 apiVersion.

https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects

**Comment by jpkrohling** [comment]
There are no side-effects, ie, out-of-band changes executed as part of any of our webhooks. The only webhook that changes anything is the pod injector, but that change isn't out-of-band.

**Review by jpkrohling — APPROVED** [review]

**Comment by bhiravabhatla** [comment]
@jpkrohling  - Just curious what mutations would be come under out-of-band changes. I have gone through the docs, dint get clear understanding.

**Comment by jpkrohling** [comment]
If we would auto-provision some resource based on the CR, this would be an out-of-band change.

**Comment by bhiravabhatla** [comment]
@jpkrohling Would need to modify the webhook manifests as well. They are in v1beta1 now. Would raise another PR.

**Pull request merged**
