### PR TITLE
Skip .NET auto-instrumentation if OTEL_DOTNET_AUTO_HOME env var is already set

### LINKED ISSUE #1156: Do not enable .NET instrumentation if OTEL_DOTNET_AUTO_HOME is already set
I think that we should additionally validate that the `dotNetOTelAutoHomePath` env var was not set in the original container. Otherwise, we cannot auto-instrument the .NET app. If someone set it then it would mean that somebody has already set the .NET AutoInstrumentation in the container.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-operator/pull/1141#discussion_r991019109_

### PR DESCRIPTION
**Pull request by avadhut123pisal**
Fixes #1156

### CODE REVIEW

**Comment by avadhut123pisal** [comment]
@pellared @Kielek  Can you please review the PR ?

**Review by pellared — APPROVED** [review]
nit comments only

@pavolloffay I think that my comments could spotted by golangci-lint. However, the current configuration is very minimal. I would consider enabling the following linters:

- [revive](https://github.com/mgechev/revive) - golint replacement
- [gosimple](https://github.com/dominikh/go-tools/tree/master/simple)  -it is enabled by default
- [staticcheck](https://staticcheck.io/) - enabled by default
- [ineffassign](https://github.com/gordonklaus/ineffassign) - enabled by default
- typecheck - enabled by default - it makes the errors better if the code does not compile 😉 
- [unused](https://github.com/dominikh/go-tools/tree/master/unused) - enabled by default
- [unparam](https://github.com/mvdan/unparam)
- [nolintlint](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/nolintlint/README.md)

**Comment by pavolloffay** [comment]
e2e test failed, I have restarted build

**Comment by avadhut123pisal** [comment]
> e2e test failed, I have restarted build

Not sure why it is failing. Error is ` for kuttl/harness/upgrade-test`. During initial run it passed and then it started failing.

**Review by pavolloffay — APPROVED** [review]

**Pull request merged**
