### PR TITLE
Add livenessProbe to target allocator deployment for operator

### PR DESCRIPTION
**Pull request by changexd**
**Description:** 
This follows #2355, this PR adds livenessProbe when creating TA deployment

**Link to tracking Issue:** <Issue number if applicable>
#2355 #2258

**Testing:** <Describe what testing was performed and which tests were added.>
I've also added additional fields to both unit tests and e2e tests just in case.

### CODE REVIEW

**Comment by swiatekm-sumo** [comment]
If the liveness probe is not implemented in this PR, then why do e2e tests pass? Do they pass before they liveness probe can restart the container?

**Comment by changexd** [comment]
That's likely the case, because after 3 consecutive failures and restarts, the pod does go into crashloop state , I'll look into this to see what can be done, sorry for not noticing this.

**Comment by swiatekm-sumo** [comment]
I don't think this is that big of a problem, but if we want to merge this independently of #2355, then it would be nice to assert that the target allocator is failing liveness probes somewhere in e2e tests.

**Comment by changexd** [comment]
I've tried different ways to test this, as I wasn't able to come up with a better solution than just checking the container restart count after a period, since the liveness probe checks 3 time * 10 period seconds by default before restarting container, I added a test step sleeps for 35 seconds and check if the status of the pod matches expected 0 restarts. 

Additionally I also added a brief timeout to prevent waiting for another default 150 seconds after a 35 second sleep time if the test fails.

If there's a better approach, please feel free to let me know :)

**Review by swiatekm-sumo — APPROVED** [review]
LGTM

We should only merge after #2355 lands.

**Comment by pavolloffay** [comment]
e2e tests failed, I am restarting it

**Pull request merged**
